[project]
authors = [
  { name = "A.suzuki", email = "suzu.devworks@gmail.com" },
]
dependencies = [
  "fastapi[standard]>=0.115.7",
  "passlib[bcrypt]>=1.7.4",
  "pyjwt>=2.10.1",
]
description = "Add your description here"
name = "examples-fastapi"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
  "types-passlib>=1.7.7.20241221",
]
