services:
  web:
    image: "nginx:alpine"
    networks:
      - interconnect
    ports:
      - "8080:80"
      - "8443:8443"
    restart: always
    volumes:
      - .devcontainer/web/nginx.conf.d:/etc/nginx/conf.d:ro
      # Use SSL server certificate
      - ~/.vscode/ssl:/etc/ssl/local:ro

networks:
  interconnect:
    driver: bridge
