[project]
authors = [
  { name = "A.suzuki", email = "suzu.devworks@gmail.com" },
]
dependencies = [
  "aiohttp-jinja2>=1.6",
  "aiohttp-session>=2.12.1",
  "aiohttp[speedups]>=3.11.11",
]
description = "Add your description here"
name = "examples-aiohttp"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
  "aiohttp-devtools>=1.1.2",
]
