[project]
authors = [
  { name = "A.suzuki", email = "suzu.devworks@gmail.com" },
]
dependencies = [
  "playwright>=1.47.0",
]
description = "Add your description here"
name = "examples-playwright-started"
readme = "README.md"
requires-python = ">= 3.12"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
  "pytest-asyncio>=0.24.0",
  "pytest-cov>=5.0.0",
  "pytest-playwright>=0.5.2",
  "pytest>=8.3.4",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/examples_playwright_started"]

[tool.pytest.ini_options]
addopts = "--durations=0 --cov-branch --cov-report xml:.cov/coverage.xml --cov=src/ -m \"not use_other_env\""
markers = ["use_other_env"]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["src/"]
